name: Continuous Integration Testing and Linting

on:
  push:
    branches:
      - main
      - develop
    paths:
    - 'server/**'
    - 'Public/docs/**'
    - 'test/**'
       
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js '14.x'
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: '4.4'
    - name: Installation des packages (rapide depuis lock file)
      run: npm ci
    - name: Lint le projet
      run: npm run lint
    - name: Test le projet
      run: npm run test
